name: deep_cartograph
channels:

  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Base depends
  - python >=3.8,<=3.10
  - pip

  # Package dependencies
  - numpy
  - pandas
  - pytorch
  - lightning
  - mdanalysis
  - seaborn
  - matplotlib
  - scikit-learn>=1.3  # HDBSCAN is included in scikit-learn>=1.3
   
  # Pip-only installs
  - pip:
    - mlcolvar
    - KDEpy            # (Optional) Faster than scikit-learn for KDE
  # - hdbscan          # Alternative to installing scikit-learn - note that the corresponding imports would have to be changed in the code