name: deep_cartograph
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.12
  - annotated-types=0.7.0
  - anyio=4.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.7.1
  - aws-c-common=0.9.23
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.10
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.6.0
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.27.3
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - biopython=1.84
  - bleach=6.1.0
  - blosc=1.21.6
  - bokeh=3.5.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - cftime=1.6.4
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.8.0
  - dask-core=2024.8.0
  - dask-expr=1.1.10
  - dbus=1.13.6
  - debugpy=1.8.5
  - decorator=5.1.1
  - defusedxml=0.7.1
  - distributed=2024.8.0
  - double-conversion=3.3.0
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - expat=2.6.2
  - fftw=3.3.10
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - gawk=5.3.1
  - gflags=2.2.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - graphite2=1.3.13
  - griddataformats=1.0.2
  - gsd=3.3.0
  - gsl=2.7
  - h11=0.14.0
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.5
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarrow=17.0.0
  - libarrow-acero=17.0.0
  - libarrow-dataset=17.0.0
  - libarrow-substrait=17.0.0
  - libasprintf=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=18.1.8
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.9.1
  - libdeflate=1.21
  - libdrm=2.4.122
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libgoogle-cloud=2.26.0
  - libgoogle-cloud-storage=2.26.0
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=17.0.0
  - libpciaccess=0.18
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libtorch=2.3.1
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libxslt=1.1.39
  - libzip=1.10.1
  - libzlib=1.3.1
  - lightning=2.3.3
  - lightning-utilities=0.11.6
  - llvm-openmp=18.1.8
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdanalysis=2.1.0
  - mistune=3.0.2
  - mkl=2023.2.0
  - mmtf-python=1.1.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mrcfile=1.5.3
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.1
  - networkx=3.3
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.43.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=17.0.0
  - pyarrow-core=17.0.0
  - pyarrow-hotfix=0.6
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pyside6=6.7.2
  - pysocks=1.7.1
  - pytest=8.3.3
  - python=3.10.0
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytorch-lightning=2.3.3
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.1.0
  - qhull=2020.2
  - qt6-main=6.7.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.19.1
  - s2n=1.4.17
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=72.1.0
  - six=1.16.0
  - sleef=3.6.1
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - sympy=1.13.0
  - tbb=2021.12.0
  - tblib=3.0.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - torchmetrics=1.4.0.post0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wayland=1.23.0
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - widgetsnbextension=4.0.11
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.4
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xyzservices=2024.6.0
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.3.5
      - aiohttp==3.10.1
      - aiosignal==1.3.1
      - async-timeout==4.0.3
      - git+https://github.com/NBDsoftware/deep_cartograph.git@master
      - diptest==0.8.0
      - frozenlist==1.4.1
      - kdepy==1.1.9
      - git+https://github.com/NBDsoftware/mlcolvar.git@main
      - multidict==6.0.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - plumed==2.9.0
      - torch==2.2.2
      - triton==2.2.0
      - yarl==1.9.4
