name: deep_cartograph
channels:

  - conda-forge
  - pytorch
  - defaults

dependencies:
  # Base depends
  - python >=3.8,<=3.10
  - pip

  # Package dependencies
  - numpy
  - dask 
  - pandas
  - pydantic
  - pytorch
  - lightning
  - mdanalysis
  - seaborn
  - matplotlib
  - scikit-learn>=1.3  # HDBSCAN is included in scikit-learn>=1.3
  - jupyter            # (Optional) For running the notebooks
   
  # Pip-only installs
  - pip:   
    - KDEpy                                                        # (Optional) Faster than scikit-learn for KDE
    - diptest
    - plumed==2.9.0                                                # (Optional) Otherwise use an external installation
    - git+https://github.com/NBDsoftware/mlcolvar.git@main         # Custom mlcolvar version with lr scheduler support
    - git+https://github.com/NBDsoftware/deep_cartograph.git@master 
  # - hdbscan                                                      # Alternative to installing scikit-learn - note that the corresponding imports would have to be changed
