name: mlcolvar_utils
channels:

  - conda-forge
  - pytorch

  - defaults
dependencies:
    # Base depends
  - python
  - pip

    # Package dependencies
  - numpy
  - pandas
  - pytorch
  - pydantic<2
  - lightning
  - matplotlib
  - scikit-learn
  - scipy<1.11
   
    # Pip-only installs
  - pip:
    - KDEpy
    - nbmake

